### ISSUE TITLE
circus statsd not work with psutil 2.1.0

### ISSUE THREAD

**Issue by lovesky** [circus-tent/circus#760]
``` python
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/circus/controller.py", line 178, in dispatch
    resp = cmd.execute(self.arbiter, properties)
  File "/usr/local/python/lib/python2.7/site-packages/circus/commands/dstats.py", line 64, in execute
    return {'info': get_info(interval=0.01)}
  File "/usr/local/python/lib/python2.7/site-packages/circus/util.py", line 181, in get_info
    cmdline = os.path.basename(shlex.split(process.cmdline[0])[0])
TypeError: 'instancemethod' object has no attribute '__getitem__'
```

psutil 1.2.1 works fine.
