### PR TITLE
FIX #939 TypeError in ConfigParser on Python 3.5

### LINKED ISSUE #939: TypeError when launching circusd
It seems that this version of circus should work with Python 3.4, but not for me:
```
> circusd app.ini 
Traceback (most recent call last):
  File "/home/bertrand/venv/bin/circusd", line 9, in <module>
    load_entry_point('circus==0.12.1', 'console_scripts', 'circusd')()
  File "/home/bertrand/venv/lib/python3.4/site-packages/circus/circusd.py", line 126, in main
    arbiter = Arbiter.load_from_config(args.config)
  File "/home/bertrand/venv/lib/python3.4/site-packages/circus/arbiter.py", line 423, in load_from_config
    cfg = get_config(config_file)
  File "/home/bertrand/venv/lib/python3.4/site-packages/circus/config.py", line 211, in get_config
    for opt, val in cfg.items(section, noreplace=True):
  File "/home/bertrand/venv/lib/python3.4/site-packages/circus/config.py", line 64, in items
    items = StrictConfigParser.items(self, section)
  File "/usr/lib/python3.4/configparser.py", line 835, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.4/configparser.py", line 835, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.4/configparser.py", line 832, in <lambda>
    section, option, d[option], d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
```

Versions:
```
> python --version
Python 3.4.3+
> circusd --version
0.12.1
```

### PR DESCRIPTION
**Pull request by maciekcz**

### CODE REVIEW

**Comment by k4nar** [comment]
Thanks :+1: .

However there is something I really don't understand about it. Without this change, some tests should fail with Python 3.4, but they do pass on Travis :/ .

**Comment by maciekcz** [comment]
Should I do something more to make this fix accepted?

**Comment by k4nar** [comment]
No, I'll merge it. Thank you for your work!

I was just taking some time to see why our tests were passing on Python 3.4 despite this bug. It might be due to a difference between Python 3.4.2 and 3.4.3 but I wasn't able to find out.
