### ISSUE TITLE
TypeError when launching circusd

### ISSUE THREAD

**Issue by bbc2** [circus-tent/circus#939]
It seems that this version of circus should work with Python 3.4, but not for me:
```
> circusd app.ini 
Traceback (most recent call last):
  File "/home/bertrand/venv/bin/circusd", line 9, in <module>
    load_entry_point('circus==0.12.1', 'console_scripts', 'circusd')()
  File "/home/bertrand/venv/lib/python3.4/site-packages/circus/circusd.py", line 126, in main
    arbiter = Arbiter.load_from_config(args.config)
  File "/home/bertrand/venv/lib/python3.4/site-packages/circus/arbiter.py", line 423, in load_from_config
    cfg = get_config(config_file)
  File "/home/bertrand/venv/lib/python3.4/site-packages/circus/config.py", line 211, in get_config
    for opt, val in cfg.items(section, noreplace=True):
  File "/home/bertrand/venv/lib/python3.4/site-packages/circus/config.py", line 64, in items
    items = StrictConfigParser.items(self, section)
  File "/usr/lib/python3.4/configparser.py", line 835, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.4/configparser.py", line 835, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.4/configparser.py", line 832, in <lambda>
    section, option, d[option], d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
```

Versions:
```
> python --version
Python 3.4.3+
> circusd --version
0.12.1
```

**Comment by k4nar** [comment]
I think I found the error, `DefaultConfigParser.get` should take `**kwargs`, cf https://github.com/circus-tent/circus/blob/610195a247e32f2466614aabdc85908685c00bae/circus/config.py#L60.

What's surprising here is that a lot of people are using Circus with Python 3.4, and we never saw this error before. Could you paste your `app.ini` file please ?

**Comment by bbc2** [comment]
Sure!
```
[watcher:web]
cmd = python app.py
numprocesses = 1
```

**Comment by barrychapman** [comment]
I am also having this problem - is tehre a fix?

**Comment by k4nar** [comment]
I don't have any time to fix this right now, but I would be happy to review a Pull-Request.
